In [7]:
import numpy as np
a=np.random.randint(1,20,3)
a

array([17,  3, 16])

In [11]:
a=np.random.rand(4)
a

array([0.04619864, 0.96997565, 0.53725522, 0.73600487])

In [13]:
a=np.random.randn(5)
a

array([ 0.8428778 , -0.85747278,  0.02684514,  0.13249227, -0.65941411])

In [15]:
np.random.seed(34)
a=np.random.randint(1,20,4)
a

array([ 2, 11, 10,  5])

In [16]:
a=np.random.randint(1,100,36)
a

array([36, 70, 12, 79, 30, 19, 30, 90, 30, 21, 97, 63,  6, 21, 52, 20, 86,
       22, 64, 73, 43, 85, 73, 78, 37,  3, 38, 99, 59, 43, 76, 35, 59, 63,
       39, 89])

In [17]:
a.reshape(2,18)

array([[36, 70, 12, 79, 30, 19, 30, 90, 30, 21, 97, 63,  6, 21, 52, 20,
        86, 22],
       [64, 73, 43, 85, 73, 78, 37,  3, 38, 99, 59, 43, 76, 35, 59, 63,
        39, 89]])

In [18]:
a.reshape(18,2)

array([[36, 70],
       [12, 79],
       [30, 19],
       [30, 90],
       [30, 21],
       [97, 63],
       [ 6, 21],
       [52, 20],
       [86, 22],
       [64, 73],
       [43, 85],
       [73, 78],
       [37,  3],
       [38, 99],
       [59, 43],
       [76, 35],
       [59, 63],
       [39, 89]])

In [19]:
a.reshape(3,12)

array([[36, 70, 12, 79, 30, 19, 30, 90, 30, 21, 97, 63],
       [ 6, 21, 52, 20, 86, 22, 64, 73, 43, 85, 73, 78],
       [37,  3, 38, 99, 59, 43, 76, 35, 59, 63, 39, 89]])

In [20]:
a.reshape(12,3)

array([[36, 70, 12],
       [79, 30, 19],
       [30, 90, 30],
       [21, 97, 63],
       [ 6, 21, 52],
       [20, 86, 22],
       [64, 73, 43],
       [85, 73, 78],
       [37,  3, 38],
       [99, 59, 43],
       [76, 35, 59],
       [63, 39, 89]])

In [21]:
a.reshape(4,9)

array([[36, 70, 12, 79, 30, 19, 30, 90, 30],
       [21, 97, 63,  6, 21, 52, 20, 86, 22],
       [64, 73, 43, 85, 73, 78, 37,  3, 38],
       [99, 59, 43, 76, 35, 59, 63, 39, 89]])

In [22]:
a.reshape(9,4)

array([[36, 70, 12, 79],
       [30, 19, 30, 90],
       [30, 21, 97, 63],
       [ 6, 21, 52, 20],
       [86, 22, 64, 73],
       [43, 85, 73, 78],
       [37,  3, 38, 99],
       [59, 43, 76, 35],
       [59, 63, 39, 89]])

In [23]:
a.reshape(6,6)

array([[36, 70, 12, 79, 30, 19],
       [30, 90, 30, 21, 97, 63],
       [ 6, 21, 52, 20, 86, 22],
       [64, 73, 43, 85, 73, 78],
       [37,  3, 38, 99, 59, 43],
       [76, 35, 59, 63, 39, 89]])

In [25]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [28]:
a=np.array([10,20,30,10,40,10,20,10,50,20,10,40,50])
np.unique(a,return_index=True,return_counts=True)


(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 4, 8], dtype=int64),
 array([5, 3, 1, 2, 2], dtype=int64))

In [29]:
a=np.array([10,20,30,40,50])
b=a[2:4]
b[:]=0
a

array([10, 20,  0,  0, 50])

In [30]:
a=np.array([10,20,30,40,50])
b=a[2:4].copy()
b[:]=0
a

array([10, 20, 30, 40, 50])

In [34]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [35]:
a[a>10]

array([11, 12, 13, 14, 15])

In [36]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [37]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [38]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [44]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [40]:
a+b


array([[ 6,  8],
       [10, 12]])

In [41]:
a-b

array([[-4, -4],
       [-4, -4]])

In [42]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [45]:
a*2

array([[2, 4],
       [6, 8]])

In [46]:
a**2

array([[ 1,  4],
       [ 9, 16]])

In [47]:
a**3

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [48]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [49]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [50]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [51]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [52]:
import numpy as np

In [53]:
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [60]:
a=np.random.randint(1,100,10)
a

array([43, 97, 44, 86, 32, 85, 90, 63, 85, 91])

In [61]:
a=np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [76]:
a=np.arange(1,10)
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
a=np.ones(10)*5
a

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [70]:
a=np.random.rand(3,3)
a

array([[0.41238758, 0.62179133, 0.84674081],
       [0.13643667, 0.46137441, 0.03341119],
       [0.91255129, 0.08363438, 0.62074326]])

In [72]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [73]:
b=np.arange(5,9)
b

array([5, 6, 7, 8])

In [74]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [75]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])