In [1]:
#Numpy ==> numerical python ==> open source library

In [2]:
import numpy as np

In [4]:
a=[1,2,3,4,5]
b=np.array(a)
b

array([1, 2, 3, 4, 5])

In [6]:
a=[]
size=int(input("enter the no.:"))
for i in range(size):
    val=int(input("enter the values:"))
    a.append(val)
b=np.array(a)
b

enter the no.:3
enter the values:1
enter the values:2
enter the values:3


array([1, 2, 3])

In [7]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
print("no. of dim.:",b.ndim)
print("shape:",b.shape)
print("size:",b.size)

no. of dim.: 2
shape: (3, 3)
size: 9


In [9]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [11]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
print("no. of dim.:",a.ndim)
print("shape:",a.shape)
print("size:",a.size)

no. of dim.: 2
shape: (3, 4)
size: 12


In [13]:
a=np.ones(3)
a

array([1., 1., 1.])

In [16]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
print("no. of dim.:",a.ndim)
print("shape:",a.shape)
print("size:",a.size)

no. of dim.: 2
shape: (3, 4)
size: 12


In [18]:
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [19]:
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])