In [1]:
print("hello world")

hello world


In [3]:
print("hey",end=" ")
print("regex")

hey regex


In [5]:
x=10
print(type(x))

<class 'int'>


In [6]:
x="10"
print(type(x))

<class 'str'>


In [7]:
# indexing and slicing
company = "regex software"
company[2]

'g'

In [8]:
company[-2]

'r'

In [9]:
company[0:]

'regex software'

In [10]:
company[2:]

'gex software'

In [12]:
company[0:5]

'regex'

In [21]:
company[-1::-1]

'erawtfos xeger'

In [24]:
# conditional statement
if(True):
    print("hello")
else:
    print("world")


hello


In [26]:
x=10
if(x==20):
    print("Value is 20")
elif(x==10):
    print("Value is 10")
else:
    print("Value is not 20")

Value is 10


In [42]:
# datatypes:-
# list => data is stored based on index, list are mutable datatype.
mylist=[10,20,"regex",10.0]
print(type(mylist))

<class 'list'>


In [30]:
mylist[2]

'regex'

In [43]:
mylist[-2]="regexsoftware"
mylist

[10, 20, 'regexsoftware', 10.0]

In [44]:
mylist.append(60)# add at last index
mylist

[10, 20, 'regexsoftware', 10.0, 60]

In [45]:
mylist.pop(0) # by default last index
mylist

[20, 'regexsoftware', 10.0, 60]

In [46]:
mylist.remove(60)
mylist

[20, 'regexsoftware', 10.0]

In [47]:
mylist.insert(0,10)
mylist

[10, 20, 'regexsoftware', 10.0]

In [49]:
# tuple => immutable datatype
mytuple=(10,20,30,"abc")
mytuple

(10, 20, 30, 'abc')

In [51]:
# help(mytuple)

In [54]:
# dictionary => data stores as key:value pair,immutable datatype
# keys are unique identifier
# in python 3 data stored in ordered
mydict={7:"nikhil",10:"aman",11:"aditya"}
mydict

{7: 'nikhil', 10: 'aman', 11: 'aditya'}

In [60]:
mydict[10]

'aman'

In [61]:
mydict[10]="aman sharma"
mydict

{7: 'nikhil', 10: 'aman sharma', 11: 'aditya'}

In [62]:
mydict[22]="naina"
mydict

{7: 'nikhil', 10: 'aman sharma', 11: 'aditya', 22: 'naina'}

In [63]:
mydict.pop(11)
mydict

{7: 'nikhil', 10: 'aman sharma', 22: 'naina'}

In [64]:
# functions => set of statements which we reuse multiple time
def workshop():
    print("hey welcome to the workshop")

In [65]:
workshop()

hey welcome to the workshop


In [81]:
def workshop(name):
    print("hey",name,"welcome to the workshop")

In [82]:
workshop("nikhil")
workshop("ajay")

hey nikhil welcome to the workshop
hey ajay welcome to the workshop


In [83]:
def workshop(name):
    return "hey",name,"welcome to the workshop"

In [84]:
print(workshop("arun"))

('hey', 'arun', 'welcome to the workshop')


# NumPy:- 
NumPy is python library used for working with arrays.

It provides a high-performance multidimensional array object and tools for working with these arrays Mathematical functions for fast operations on entire arrays of data having to write loops.

Numpy are approx 10 to 100 time faster than list.

In [85]:
# !pip install numpy

In [90]:
import numpy as np
arr1=np.arange(10) # create array in a range
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [92]:
my_arr=np.arange(10000)
my_list=list(range(10000))

In [94]:
# my_list

In [95]:
arr1+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
arr1+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [101]:
%timeit my_arr+10 # to check time of running

10.1 µs ± 270 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [102]:
%timeit my_list2=[x+10 for x in my_list]

724 µs ± 42.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [104]:
arr1.ndim # dimension

1

In [105]:
arr1.size # total elements

10

In [106]:
arr1.shape # rows and columns

(10,)

In [117]:
data2 = [[1,2,3],[3,4,5]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [118]:
arr2.ndim

2

In [135]:
arr2.shape

(2, 3)

In [120]:
arr2[0][1]

2

In [121]:
arr2[1][0]

3

In [122]:
arr2[0][0:2]

array([1, 2])

In [125]:
arr2.dtype

dtype('int32')

In [126]:
arr3=np.array([1.2,-2.3,4.3])
arr3.dtype  # check datatype

dtype('float64')

In [129]:
arr3.astype(np.int32) # change datatype

array([ 1, -2,  4])

In [130]:
arr3[0:2]

array([ 1.2, -2.3])

In [131]:
arr3[0]=30.89
arr3

array([30.89, -2.3 ,  4.3 ])

# Pandas:-
Most powerful library for data manipulation, data cleaning, data transforming.

Series => single dimension array of value

DataFrame => collection of series values


In [136]:
# !pip install pandas

In [140]:
import pandas as pd

product=["mobile","tv","laptop"]
product1=[10,20,30]
pd.Series(product1)

0    10
1    20
2    30
dtype: int64

In [141]:
array1=np.array([10,20,30,100])
type(array1)

numpy.ndarray

In [144]:
product_series=pd.Series(array1)

In [145]:
product_series.dtype

dtype('int32')

In [146]:
product_series.size

4

In [150]:
product_series.name="regexworkshop"
product_series

0     10
1     20
2     30
3    100
Name: regexworkshop, dtype: int32

In [151]:
product_series.is_unique # unique values

True

In [152]:
my_dict={"a":10,"b":20}
pd.Series(my_dict)

a    10
b    20
dtype: int64

In [157]:
data2={"Product":["Mobile","Tv","Laptop"],"Price":[6000,8000,8000]}
df=pd.DataFrame(data2)
df

Product  Price
0  Mobile   6000
1      Tv   8000
2  Laptop   8000

In [158]:
df["Price"].sum()

22000

In [159]:
df["Price"].value_counts()

Price
8000    2
6000    1
Name: count, dtype: int64

# Project:-